---
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - b2dc8dbd27916d8321e298f59fc2f431 # Erubis < ::Erubis::Eruby
    config:
      languages:
      - ruby
ratings:
  paths:
  - "**.rb"
  - Gemfile.lock
exclude_paths:
- config/**/*
- spec/**/*
- vendor/**/*
